- hosts: webservers
  become: true
  remote_user: "{{ remote_user }}"

  pre_tasks:
    - debug:
        msg: "Run on server: {{ ansible_host }}"
    - name: Load vars
      include_tasks: tasks/load-vars.yml
      when: not vars_loaded

  roles:
    - upnetix.common
    - { role: upnetix.nginx, when: app_env is defined and app_env != "dev"}
